spring.application.name=quiz-engine
spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
spring.datasource.username=root
spring.datasource.password=111111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
